version: "3.7"

services:
  web:
    build: .
    restart: always
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:14
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=config
    env_file:
      - .env
    ports:
      - "5433:5432"
  nginx:
    build: ./nginx
    restart: always
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - ./nginx:/app/nginx/
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web

volumes:
  pgdata:
  static_volume:
  media_volume:
